separated http header & changed device types
luc-github/ESP32SSDP pull request #27
Opened 2022-01-13 23:02 UTC by B4stl3r

Hi, 
I've seen you have included the header directly in the schema().

That's probably not really nice, as it just works with the Arduino included Webserver.

For the Async Webserver (https://github.com/me-no-dev/ESPAsyncWebServer) it's not working out of the box.
Therefore someone wrote a Wrapper of your lib: https://github.com/Lightwell-bg/ssdpAWS

Now it could be used in general and per default, header will be included, so compatible with everything.

Cheers.

2022-01-13 23:10 UTC, B4stl3r commented
ah, forgot to set the default in the .h file..:

const char * schema(bool includeheader = true);

2022-01-14 06:34 UTC, luc-github requested changes
Could you push the PR to Devt branch ?
even PR looks good to me, it still need to do some testing and also need version change so better to apply to devt branch first

2022-01-14 06:38 UTC, luc-github commented
Thank  you for the PR, indeed will simplify integration with asyncwebserver

I feel confused by  https://github.com/Lightwell-bg/ssdpAWS, reading at code it looks it only serve the xml file to web server and do not do SSDP at all - it seems misleading

2022-01-14 09:20 UTC, B4stl3r commented
Hi, 
couple of answers / questions ;)

1. ssdpAWS.. yes, it looked also strange to me, so I dig into it, what and why it's not working with your lib directly and found the reason. It's working, cause the SSDP broadcast is started (with your lib), but the description is served separately (which is just waste of flash and heap ;)

2. Your devbranch is already ahead of master, I didn't test this one, just the changes from master. So how you want to proceed?

3. found yesterday after the PR following in the .cpp (~ line 585):
strlcpy(_respondType, "upnp:rootdevice", sizeof(_respondType));
strlcpy(_usn_suffix, "::upnp:rootdevice", sizeof(_usn_suffix));

Do we need to change the device type here also?
It is advised correctly:
![grafik](https://user-images.githubusercontent.com/73077761/149490191-4022c488-2d31-4fb0-a322-f53b5656cc45.png)

but in the broadcast:
![grafik](https://user-images.githubusercontent.com/73077761/149490700-178469c0-222d-4097-b10b-25f13e3d1a44.png)

please advise ;)

2022-01-14 15:07 UTC, luc-github commented
sorry I missed your questions, but I see you managed and created new pr , so this on can be closed I guess?

2022-01-14 15:29 UTC, B4stl3r commented
yep, sure.

2022-01-14 15:29 UTC, closed without merging